In [1]:
!pip install -U scikit-learn

In [2]:
import numpy as np
import pandas as pd

# soale 1


In [88]:
df = pd.read_csv('/content/Maternal Health Risk Data Set.csv')
y = df.iloc[:, 6:7]
X = df.iloc[:, 0:6]
df.head()

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [89]:
y.loc[(y["RiskLevel"] == "low risk")] = 0
y.loc[(y["RiskLevel"] == "mid risk")] = 1
y.loc[(y["RiskLevel"] == "high risk")] = 2
y

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:723: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


RiskLevel
0            2
1            2
2            2
3            2
4            0
...        ...
1009         2
1010         2
1011         2
1012         2
1013         1

[1014 rows x 1 columns]

In [90]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler().fit(X)
print(X)
X = pd.DataFrame(scaler.transform(X))

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
0      25         130           80  15.0      98.0         86
1      35         140           90  13.0      98.0         70
2      29          90           70   8.0     100.0         80
3      30         140           85   7.0      98.0         70
4      35         120           60   6.1      98.0         76
...   ...         ...          ...   ...       ...        ...
1009   22         120           60  15.0      98.0         80
1010   55         120           90  18.0      98.0         60
1011   35          85           60  19.0      98.0         86
1012   43         120           90  18.0      98.0         70
1013   32         120           65   6.0     101.0         76

[1014 rows x 6 columns]


In [91]:
idx = np.random.permutation(X.index)
X = X.reindex(idx)
y = y.reindex(idx)

In [92]:
n = X.shape[0]
n = int(0.7 * n)
X_train = X.iloc[:n,]
X_test = X.iloc[n:,]
y_train = y.iloc[:n,]
y_train = y_train.astype('int')
y_test = y.iloc[n:,]
y_test = y_test.astype('int')

In [93]:
from sklearn import tree
from sklearn.metrics import confusion_matrix
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, np.array(y_train))
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(clf.score(X_test, y_test))

[[94 25  3]
 [15 80  7]
 [ 2  6 73]]
0.8098360655737705


In [94]:
from sklearn.neighbors import KNeighborsClassifier
neigh1 = KNeighborsClassifier(n_neighbors=1)
neigh2 = KNeighborsClassifier(n_neighbors=2)
neigh3 = KNeighborsClassifier(n_neighbors=3)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(neigh1, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(neigh2, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(neigh3, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())

neigh1.fit(X_train, np.array(y_train).ravel())
y_pred = neigh1.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(neigh1.score(X_test, y_test))

[0.76760563 0.78169014 0.77464789 0.74647887 0.79432624] 0.7729497552692038 0.015909112923928055
[0.72535211 0.71830986 0.6971831  0.6971831  0.70921986] 0.7094496054340225 0.01124616376037998
[0.74647887 0.67605634 0.65492958 0.6971831  0.67375887] 0.689681350514434 0.031397729358369854
[[95 22  5]
 [14 84  4]
 [ 2 13 66]]
0.8032786885245902


In [95]:
from sklearn import svm
svmcl = svm.SVC()
svmcl = svmcl.fit(X_train, np.array(y_train).ravel())
y_pred = svmcl.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(svmcl.score(X_test, y_test))

[[101  13   8]
 [ 45  41  16]
 [  3   9  69]]
0.6918032786885245


In [97]:
from sklearn.ensemble import RandomForestClassifier
rfc1 = RandomForestClassifier(n_estimators = 10)
rfc2 = RandomForestClassifier(n_estimators = 50)
rfc3 = RandomForestClassifier(n_estimators = 100)
rfc4 = RandomForestClassifier(n_estimators = 400)

scores = cross_val_score(rfc1, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(rfc2, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(rfc3, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(rfc4, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())

rfc3 = rfc3.fit(X_train, np.array(y_train).ravel())
y_pred = rfc3.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(rfc3.score(X_test, y_test))

[0.81690141 0.78873239 0.82394366 0.80985915 0.80851064] 0.8095894516032365 0.011796283167729595
[0.80985915 0.83098592 0.81690141 0.77464789 0.82978723] 0.8124363200479472 0.020492370042774898
[0.79577465 0.83098592 0.81690141 0.79577465 0.84397163] 0.8166816501847969 0.01909769019517587
[0.80985915 0.82394366 0.80985915 0.79577465 0.82978723] 0.8138447707521725 0.011953655064062966
[[99 18  5]
 [12 83  7]
 [ 2  6 73]]
0.8360655737704918


be joz svm baghie model ha taghriban deghate yeksan dashtand. knn va decision tree meghdare kami deghatash kamtar az algorithme digar bood va random forest behtarin natije ra dasht.
ba crossvalidation dar knn didim ke k = 1 behtarin halat ast va ba crossvalidation dar random forest didim ke n_estimators tasire ziade nadarad va az haman meghdare default yani 100 estefade kardim

# soale 2

In [135]:
df = pd.read_csv('/content/pd_speech_features.csv')
y = df.iloc[:, 754:]
X = df.iloc[:, :754]
df.head()

id  gender      PPE      DFA     RPDE  numPulses  numPeriodsPulses  \
0   0       1  0.85247  0.71826  0.57227        240               239   
1   0       1  0.76686  0.69481  0.53966        234               233   
2   0       1  0.85083  0.67604  0.58982        232               231   
3   1       0  0.41121  0.79672  0.59257        178               177   
4   1       0  0.32790  0.79782  0.53028        236               235   

   meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...  \
0          0.008064            0.000087       0.00218  ...   
1          0.008258            0.000073       0.00195  ...   
2          0.008340            0.000060       0.00176  ...   
3          0.010858            0.000183       0.00419  ...   
4          0.008162            0.002669       0.00535  ...   

   tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
0                     1.5620                     2.6445   
1                     1.5589                     3.6107   
2                     1.5643                     2.3308   
3                     3.7805                     3.5664   
4                     6.1727                     5.8416   

   tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
0                     3.8686                     4.2105   
1                    23.5155                    14.1962   
2                     9.4959                    10.7458   
3                     5.2558                    14.0403   
4                     6.0805                     5.7621   

   tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
0                     5.1221                     4.4625   
1                    11.0261                     9.5082   
2                    11.0177                     4.8066   
3                     4.2235                     4.6857   
4                     7.7817                    11.6891   

   tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
0                     2.6202                     3.0004   
1                     6.5245                     6.3431   
2                     2.9199                     3.1495   
3                     4.8460                     6.2650   
4                     8.2103                     5.0559   

   tqwt_kurtosisValue_dec_36  class  
0                    18.9405      1  
1                    45.1780      1  
2                     4.7666      1  
3                     4.0603      1  
4                     6.1164      1  

[5 rows x 755 columns]

In [136]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler().fit(X)
X = pd.DataFrame(scaler.transform(X))

In [137]:
idx = np.random.permutation(X.index)
X = X.reindex(idx)
y = y.reindex(idx)

In [138]:
n = X.shape[0]
n = int(0.7 * n)
X_train = X.iloc[:n,]
X_test = X.iloc[n:,]
y_train = y.iloc[:n,]
y_train = y_train.astype('int')
y_test = y.iloc[n:,]
y_test = y_test.astype('int')

In [139]:
y_pred_train = np.full(n, 1)
dif = np.array(y_train).ravel() - y_pred_train
print(np.count_nonzero(dif != 0) / dif.shape[0] * 100)
y_pred_test = np.full(X.shape[0] - n, 1)
dif = np.array(y_test).ravel() - y_pred_test
print(np.count_nonzero(dif != 0) / dif.shape[0] * 100)


26.27599243856333
23.348017621145374


natije giri: hodoode 25 darsad az label ha 1 ast dar natije agar model hame ra 0 tashkhis bedahad deghat 75 darsadi khahad dasht. pas modeli ke deghate kamtar az 75 darsad darad be darde ma nemikhorad.

In [106]:
from sklearn import tree
from sklearn.metrics import confusion_matrix
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, np.array(y_train))
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(clf.score(X_test, y_test))

[[ 38  25]
 [ 30 134]]
0.7577092511013216


In [113]:
from sklearn.neighbors import KNeighborsClassifier
neigh1 = KNeighborsClassifier(n_neighbors=1)
neigh2 = KNeighborsClassifier(n_neighbors=2)
neigh3 = KNeighborsClassifier(n_neighbors=3)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(neigh1, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(neigh2, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(neigh3, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())

neigh1.fit(X_train, np.array(y_train).ravel())
y_pred = neigh1.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(neigh1.score(X_test, y_test))

[0.88679245 0.91509434 0.86792453 0.9245283  0.96190476] 0.9112488769092544 0.0323489265876938
[0.83962264 0.83962264 0.82075472 0.90566038 0.86666667] 0.8544654088050315 0.029484985073166357
[0.8490566  0.85849057 0.83962264 0.90566038 0.9047619 ] 0.8715184186882301 0.028151026212039066
[[ 52  11]
 [  8 156]]
0.9162995594713657


In [108]:
from sklearn import svm
svmcl = svm.SVC()
svmcl = svmcl.fit(X_train, np.array(y_train).ravel())
y_pred = svmcl.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(svmcl.score(X_test, y_test))

[[ 28  35]
 [  4 160]]
0.8281938325991189


In [109]:
from sklearn.ensemble import RandomForestClassifier
rfc1 = RandomForestClassifier(n_estimators = 10)
rfc2 = RandomForestClassifier(n_estimators = 50)
rfc3 = RandomForestClassifier(n_estimators = 100)
rfc4 = RandomForestClassifier(n_estimators = 200)

scores = cross_val_score(rfc1, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(rfc2, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(rfc3, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(rfc4, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())

rfc3 = rfc3.fit(X_train, np.array(y_train).ravel())
y_pred = rfc3.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(rfc3.score(X_test, y_test))

[0.80188679 0.85849057 0.77358491 0.85849057 0.85714286] 0.8299191374663073 0.03558972327616699
[0.85849057 0.83962264 0.82075472 0.87735849 0.88571429] 0.8563881401617252 0.023895695831010824
[0.8490566  0.85849057 0.80188679 0.90566038 0.86666667] 0.8563522012578616 0.033352551716244
[0.85849057 0.85849057 0.81132075 0.90566038 0.88571429] 0.8639353099730457 0.03175810740737896
[[ 34  29]
 [  6 158]]
0.8458149779735683


random forest va svm hodoodan 83 darsad deghat dashtand va decision tree 75 darsad. dar natije decision tree modele khoobi nist. va knn 91 darsad deghat dasht ke behtarin model ast. random forest va svm ba vojoode inke deghateshan az 75 bishtar ast meghadare ghabele tavajohi bishtar nist va in baes mishavad ke kheili model haye khoobi nabashand vali hamchenan az decision tree behtar boodeand

In [129]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X)
X_reduced= pca.transform(X)

In [130]:
n = X.shape[0]
n = int(0.7 * n)
X_train = X.iloc[:n,]
X_test = X.iloc[n:,]
y_train = y.iloc[:n,]
y_train = y_train.astype('int')
y_test = y.iloc[n:,]
y_test = y_test.astype('int')

In [131]:
from sklearn import tree
from sklearn.metrics import confusion_matrix
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, np.array(y_train))
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(clf.score(X_test, y_test))

[[ 42  21]
 [ 35 129]]
0.7533039647577092


In [132]:
from sklearn.neighbors import KNeighborsClassifier
neigh1 = KNeighborsClassifier(n_neighbors=1)
neigh2 = KNeighborsClassifier(n_neighbors=2)
neigh3 = KNeighborsClassifier(n_neighbors=3)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(neigh1, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(neigh2, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(neigh3, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())

neigh1.fit(X_train, np.array(y_train).ravel())
y_pred = neigh1.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(neigh1.score(X_test, y_test))

[0.88679245 0.91509434 0.86792453 0.9245283  0.96190476] 0.9112488769092544 0.0323489265876938
[0.83962264 0.83962264 0.82075472 0.90566038 0.86666667] 0.8544654088050315 0.029484985073166357
[0.8490566  0.85849057 0.83962264 0.90566038 0.9047619 ] 0.8715184186882301 0.028151026212039066
[[ 52  11]
 [  8 156]]
0.9162995594713657


In [133]:
from sklearn import svm
svmcl = svm.SVC()
svmcl = svmcl.fit(X_train, np.array(y_train).ravel())
y_pred = svmcl.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(svmcl.score(X_test, y_test))

[[ 28  35]
 [  4 160]]
0.8281938325991189


In [134]:
from sklearn.ensemble import RandomForestClassifier
rfc1 = RandomForestClassifier(n_estimators = 10)
rfc2 = RandomForestClassifier(n_estimators = 50)
rfc3 = RandomForestClassifier(n_estimators = 100)
rfc4 = RandomForestClassifier(n_estimators = 200)

scores = cross_val_score(rfc1, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(rfc2, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(rfc3, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())
scores = cross_val_score(rfc4, X_train, np.array(y_train).ravel(), cv = 5)
print(scores, scores.mean(), scores.std())

rfc3 = rfc3.fit(X_train, np.array(y_train).ravel())
y_pred = rfc3.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(rfc3.score(X_test, y_test))

[0.82075472 0.80188679 0.81132075 0.86792453 0.81904762] 0.8241868823000897 0.022864840736440923
[0.8490566  0.86792453 0.80188679 0.89622642 0.88571429] 0.8601617250673854 0.03326604222504493
[0.85849057 0.86792453 0.81132075 0.91509434 0.87619048] 0.8658041329739443 0.033358127767761064
[0.8490566  0.85849057 0.81132075 0.90566038 0.86666667] 0.8582389937106918 0.030349675525080503
[[ 37  26]
 [  1 163]]
0.8810572687224669


ba anjame PCA va kam kardane dimension e dade didim ke meghdare kami deghate model ha taghir kardand( maghadire 200, 100, 50, 20, 10, 2 test shod) va hich kodam az in maghadir tasire cheshm giri nadasht va faghat rooye random forest tasir gozar bood meghdare kami. vali behtarin model ra avaz nakard(knn ba 91 darsad)
